export const routes = {
  root: '/',
  onboarding: '/(onboarding)',
  onboardingStep2: '/(onboarding)/step-2',
  onboardingStep3: '/(onboarding)/step-3',
  onboardingLifestyleIntro: '/(onboarding)/step-3',
  onboardingStep4: '/(onboarding)/step-4',
  onboardingMeasurementChoice: '/(onboarding)/measurement-choice',
  onboardingBodyMeasurements: '/(onboarding)/body-measurements',
  onboardingStep5: '/(onboarding)/step-5',
  authSignIn: '/(auth)/sign-in',
  authSignUp: '/(auth)/sign-up',
  authCheckEmail: '/(auth)/check-email',
  authForgotPassword: '/(auth)/forgot-password',
  authCallback: '/auth/callback',
  authRecoveryCallback: '/auth/recovery-callback',
  authResetPassword: '/auth/reset-password',
  home: '/(tabs)/home',
  coach: '/(tabs)/coach',
  progress: '/(tabs)/progress',
  progressTrends: '/(tabs)/progress/trends',
  health: '/(tabs)/health',

  healthNewMeasurement: '/(tabs)/health/new-measurement',
  healthMeasurementHistory: '/(tabs)/health',
  profile: '/(tabs)/profile',
  profileAccount: '/(tabs)/profile/account',
  profileLanguage: '/(tabs)/profile/language',
  profileHealthProfile: '/(tabs)/profile/health-profile',
  profileHealthDataSources: '/(tabs)/profile/health-data-sources',
  healthScore: '/health-score',
  weeklyCheckIn: '/weekly-check-in',
} as const;
