export const routes = {
  root: '/',
  onboarding: '/(onboarding)',
  onboardingStep2: '/(onboarding)/step-2',
  onboardingStep3: '/(onboarding)/step-3',
  onboardingStep4: '/(onboarding)/step-4',
  onboardingMeasurementChoice: '/(onboarding)/measurement-choice',
  onboardingBodyMeasurements: '/(onboarding)/body-measurements',
  onboardingStep5: '/(onboarding)/step-5',
  authSignIn: '/(auth)/sign-in',
  authSignUp: '/(auth)/sign-up',
  home: '/(tabs)/home',
  coach: '/(tabs)/coach',
  progress: '/(tabs)/progress',
  health: '/(tabs)/health',
  healthNewMeasurement: '/(tabs)/health/new-measurement',
  healthMeasurementHistory: '/(tabs)/health',
  profile: '/(tabs)/profile',
  profileHealthProfile: '/(tabs)/profile/health-profile',
  profileHealthDataSources: '/(tabs)/profile/health-data-sources',
  healthScore: '/health-score',
} as const;
