import type { CoachSimulatorTestData } from './coachSimulator.types';

export type CoachScenarioExpectation = {
  topStrength: string;
  topOpportunity: string;
  coachGoal: string;
  recommendedAction: string;
  confidenceMin: number;
  confidenceMax: number;
  insufficientData?: boolean;
  silenceEligible?: boolean;
};

export type CoachScenario = {
  id: string;
  label: string;
  description: string;
  data: CoachSimulatorTestData;
  expectation: CoachScenarioExpectation;
};

export const COACH_SCENARIOS: CoachScenario[] = [
  {
    id: 'positiv-utveckling',
    label: 'Positiv utveckling',
    description: 'Health Score up, waist down, activity up',
    data: {
      healthScore: 82,
      healthScoreDelta: 5,
      trend: 'improving',
      weightKg: 84,
      weightDeltaKg: -1.2,
      waistCm: 87,
      waistDeltaCm: -2,
      neckCm: 40,
      activity: 'Hög',
      activityTrend: 'up',
      sleep: 'Medel',
      daysSinceLastMeasurement: 7,
      dataCompleteness: 'complete',
    },
    expectation: {
      topStrength: 'Midjemått',
      topOpportunity: 'Sömn',
      coachGoal: 'Motivate',
      recommendedAction: 'Förstärk positiv trend',
      confidenceMin: 78,
      confidenceMax: 98,
    },
  },
  {
    id: 'health-score-ned',
    label: 'Health Score ned',
    description: 'Health Score down with one identifiable negative driver',
    data: {
      healthScore: 70,
      healthScoreDelta: -7,
      trend: 'declining',
      weightKg: 86,
      weightDeltaKg: 1.1,
      waistCm: 92,
      waistDeltaCm: 1.4,
      neckCm: 41,
      activity: 'Låg',
      activityTrend: 'down',
      sleep: 'Dålig',
      daysSinceLastMeasurement: 5,
      dataCompleteness: 'complete',
    },
    expectation: {
      topStrength: 'Health Score',
      topOpportunity: 'Sömn',
      coachGoal: 'Stöd',
      recommendedAction: 'Stöd återhämtning',
      confidenceMin: 55,
      confidenceMax: 78,
    },
  },
  {
    id: 'vikt-upp-midja-ned',
    label: 'Vikt upp, midja ned',
    description: 'Weight slightly increased but waist improved',
    data: {
      healthScore: 79,
      healthScoreDelta: 1,
      trend: 'stable',
      weightKg: 86.2,
      weightDeltaKg: 0.8,
      waistCm: 88,
      waistDeltaCm: -1.2,
      neckCm: 40,
      activity: 'Medel',
      activityTrend: 'stable',
      sleep: 'Medel',
      daysSinceLastMeasurement: 6,
      dataCompleteness: 'complete',
    },
    expectation: {
      topStrength: 'Midjemått',
      topOpportunity: 'Sömn',
      coachGoal: 'Guida',
      recommendedAction: 'Bekräfta stabil trend',
      confidenceMin: 68,
      confidenceMax: 92,
    },
  },
  {
    id: 'somn-mojlighet',
    label: 'Sömn som största möjlighet',
    description: 'Stable body measurements, insufficient sleep',
    data: {
      healthScore: 77,
      healthScoreDelta: 0,
      trend: 'stable',
      weightKg: 85,
      weightDeltaKg: 0.1,
      waistCm: 89,
      waistDeltaCm: -0.1,
      neckCm: 40,
      activity: 'Medel',
      activityTrend: 'stable',
      sleep: 'Dålig',
      daysSinceLastMeasurement: 5,
      dataCompleteness: 'complete',
    },
    expectation: {
      topStrength: 'Stabil bas',
      topOpportunity: 'Sömn',
      coachGoal: 'Guida',
      recommendedAction: 'Adressera sömn',
      confidenceMin: 65,
      confidenceMax: 88,
    },
  },
  {
    id: 'aktivitet-minskar',
    label: 'Aktivitet minskar',
    description: 'Lower activity than previous period',
    data: {
      healthScore: 76,
      healthScoreDelta: -1,
      trend: 'stable',
      weightKg: 85,
      weightDeltaKg: 0.2,
      waistCm: 89,
      waistDeltaCm: 0.1,
      neckCm: 40,
      activity: 'Låg',
      activityTrend: 'down',
      sleep: 'Medel',
      daysSinceLastMeasurement: 6,
      dataCompleteness: 'complete',
    },
    expectation: {
      topStrength: 'Stabil bas',
      topOpportunity: 'Aktivitet',
      coachGoal: 'Guida',
      recommendedAction: 'Öka daglig rörelse',
      confidenceMin: 62,
      confidenceMax: 86,
    },
  },
  {
    id: 'stabil-utveckling',
    label: 'Stabil utveckling',
    description: 'No meaningful changes',
    data: {
      healthScore: 78,
      healthScoreDelta: 0,
      trend: 'stable',
      weightKg: 85,
      weightDeltaKg: 0,
      waistCm: 89,
      waistDeltaCm: 0,
      neckCm: 40,
      activity: 'Medel',
      activityTrend: 'stable',
      sleep: 'Medel',
      daysSinceLastMeasurement: 7,
      dataCompleteness: 'complete',
    },
    expectation: {
      topStrength: 'Stabil bas',
      topOpportunity: 'Sömn',
      coachGoal: 'Guida',
      recommendedAction: 'Bekräfta stabil trend',
      confidenceMin: 68,
      confidenceMax: 82,
    },
  },
  {
    id: 'ingen-matning-14',
    label: 'Ingen ny mätning på 14 dagar',
    description: 'Measurement reminder after two weeks without update',
    data: {
      healthScore: 78,
      healthScoreDelta: 1,
      trend: 'stable',
      weightKg: 85,
      weightDeltaKg: 0.2,
      waistCm: 89,
      waistDeltaCm: 0,
      neckCm: 40,
      activity: 'Medel',
      activityTrend: 'stable',
      sleep: 'Medel',
      daysSinceLastMeasurement: 14,
      dataCompleteness: 'complete',
    },
    expectation: {
      topStrength: 'Stabil bas',
      topOpportunity: 'Mätningar',
      coachGoal: 'Guida',
      recommendedAction: 'Påminn om ny mätning',
      confidenceMin: 60,
      confidenceMax: 88,
    },
  },
  {
    id: 'ingen-matning-30',
    label: 'Ingen ny mätning på 30 dagar',
    description: 'Measurement reminder after one month without update',
    data: {
      healthScore: 77,
      healthScoreDelta: 0,
      trend: 'stable',
      weightKg: 85,
      weightDeltaKg: 0,
      waistCm: 89,
      waistDeltaCm: 0,
      neckCm: 40,
      activity: 'Medel',
      activityTrend: 'stable',
      sleep: 'Medel',
      daysSinceLastMeasurement: 30,
      dataCompleteness: 'complete',
    },
    expectation: {
      topStrength: 'Stabil bas',
      topOpportunity: 'Mätningar',
      coachGoal: 'Guida',
      recommendedAction: 'Påminn om ny mätning',
      confidenceMin: 55,
      confidenceMax: 75,
    },
  },
  {
    id: 'otillracklig-data',
    label: 'Otillräcklig data',
    description: 'Too little information for a personalized recommendation',
    data: {
      healthScore: 0,
      healthScoreDelta: 0,
      trend: 'stable',
      weightKg: 0,
      weightDeltaKg: 0,
      waistCm: 0,
      waistDeltaCm: 0,
      neckCm: 0,
      activity: '',
      activityTrend: 'stable',
      sleep: '',
      daysSinceLastMeasurement: 0,
      dataCompleteness: 'insufficient',
    },
    expectation: {
      topStrength: '—',
      topOpportunity: '—',
      coachGoal: 'Tiga',
      recommendedAction: 'Ingen rekommendation',
      confidenceMin: 0,
      confidenceMax: 35,
      insufficientData: true,
      silenceEligible: true,
    },
  },
  {
    id: 'motstridiga-signaler',
    label: 'Motstridiga signaler',
    description: 'Some metrics improve while others worsen',
    data: {
      healthScore: 80,
      healthScoreDelta: 4,
      trend: 'stable',
      weightKg: 86,
      weightDeltaKg: 1,
      waistCm: 88,
      waistDeltaCm: -1.5,
      neckCm: 40,
      activity: 'Låg',
      activityTrend: 'down',
      sleep: 'Medel',
      daysSinceLastMeasurement: 8,
      dataCompleteness: 'complete',
    },
    expectation: {
      topStrength: 'Midjemått',
      topOpportunity: 'Aktivitet',
      coachGoal: 'Guida',
      recommendedAction: 'Balansera motstridiga signaler',
      confidenceMin: 58,
      confidenceMax: 82,
    },
  },
];

export const DEFAULT_COACH_SCENARIO = COACH_SCENARIOS[0];

export function getCoachScenarioById(id: string): CoachScenario | undefined {
  return COACH_SCENARIOS.find((scenario) => scenario.id === id);
}
