import { DAILY_FOCUS_ANY_DAY, type DailyFocusActionDraft } from './daily-focus.types';

const any = DAILY_FOCUS_ANY_DAY;

export const DAILY_FOCUS_ACTION_DEFINITIONS = [
  // everyday_movement — 18
  { id: 'movement_take_stairs', focusArea: 'everyday_movement', behaviorFamily: 'stairs', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'movement_keep_using_stairs', focusArea: 'everyday_movement', behaviorFamily: 'stairs', intensity: 'micro', allowedModes: ['maintain'], eligibility: any },
  { id: 'movement_park_farther', focusArea: 'everyday_movement', behaviorFamily: 'parking', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'movement_alight_one_stop_early', focusArea: 'everyday_movement', behaviorFamily: 'transit', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'movement_walk_part_of_errand', focusArea: 'everyday_movement', behaviorFamily: 'active_errand', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'movement_walk_a_short_trip', focusArea: 'everyday_movement', behaviorFamily: 'active_transport', intensity: 'normal', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'movement_stand_after_sitting', focusArea: 'everyday_movement', behaviorFamily: 'standing', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'movement_break_up_sitting', focusArea: 'everyday_movement', behaviorFamily: 'walking_break', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'movement_walk_during_call', focusArea: 'everyday_movement', behaviorFamily: 'walking_call', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'movement_after_meal_stroll', focusArea: 'everyday_movement', behaviorFamily: 'after_meal_walk', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'movement_easy_outdoor_loop', focusArea: 'everyday_movement', behaviorFamily: 'outdoor_movement', intensity: 'recovery', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'movement_active_household_task', focusArea: 'everyday_movement', behaviorFamily: 'household', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'movement_move_while_waiting', focusArea: 'everyday_movement', behaviorFamily: 'waiting', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'movement_keep_usual_movement', focusArea: 'everyday_movement', behaviorFamily: 'routine_movement', intensity: 'micro', allowedModes: ['maintain'], eligibility: any },
  { id: 'movement_one_walked_errand', focusArea: 'everyday_movement', behaviorFamily: 'active_errand', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'movement_stand_for_one_task', focusArea: 'everyday_movement', behaviorFamily: 'standing', intensity: 'micro', allowedModes: ['maintain'], eligibility: any },
  { id: 'movement_skip_one_short_ride', focusArea: 'everyday_movement', behaviorFamily: 'active_transport', intensity: 'challenge', allowedModes: ['improve'], eligibility: any },
  { id: 'movement_outdoor_reset_walk', focusArea: 'everyday_movement', behaviorFamily: 'outdoor_movement', intensity: 'normal', allowedModes: ['improve'], eligibility: any },

  // training — 14
  { id: 'training_short_session', focusArea: 'training', behaviorFamily: 'short_workout', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'training_ten_minute_start', focusArea: 'training', behaviorFamily: 'getting_started', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'training_bodyweight_strength', focusArea: 'training', behaviorFamily: 'strength', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'training_simple_strength', focusArea: 'training', behaviorFamily: 'strength', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'training_mobility_session', focusArea: 'training', behaviorFamily: 'mobility', intensity: 'micro', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'training_lighter_today', focusArea: 'training', behaviorFamily: 'active_recovery', intensity: 'recovery', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'training_plan_next_session', focusArea: 'training', behaviorFamily: 'training_planning', intensity: 'micro', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'training_lay_out_kit', focusArea: 'training', behaviorFamily: 'training_preparation', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'training_keep_usual_session', focusArea: 'training', behaviorFamily: 'session_follow_through', intensity: 'normal', allowedModes: ['maintain'], eligibility: any },
  { id: 'training_controlled_strength', focusArea: 'training', behaviorFamily: 'strength', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'training_shorter_if_busy', focusArea: 'training', behaviorFamily: 'short_workout', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'training_do_planned_session', focusArea: 'training', behaviorFamily: 'session_follow_through', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'training_gentle_warmup', focusArea: 'training', behaviorFamily: 'mobility', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'training_protect_training_day', focusArea: 'training', behaviorFamily: 'session_follow_through', intensity: 'micro', allowedModes: ['maintain'], eligibility: any },

  // sleep — 16
  { id: 'sleep_screens_off_earlier', focusArea: 'sleep', behaviorFamily: 'screen_cutoff', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'sleep_phone_outside_bedroom', focusArea: 'sleep', behaviorFamily: 'phone_away', intensity: 'challenge', allowedModes: ['improve'], eligibility: any },
  { id: 'sleep_phone_away_before_bed', focusArea: 'sleep', behaviorFamily: 'phone_away', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'sleep_keep_usual_bedtime', focusArea: 'sleep', behaviorFamily: 'bedtime', intensity: 'micro', allowedModes: ['maintain'], eligibility: any },
  { id: 'sleep_prepare_bedroom', focusArea: 'sleep', behaviorFamily: 'bedroom_prep', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'sleep_write_tomorrow_list', focusArea: 'sleep', behaviorFamily: 'next_day_parking', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'sleep_stop_work_earlier', focusArea: 'sleep', behaviorFamily: 'work_cutoff', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'sleep_dim_evening_light', focusArea: 'sleep', behaviorFamily: 'evening_light', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'sleep_morning_daylight', focusArea: 'sleep', behaviorFamily: 'morning_light', intensity: 'micro', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'sleep_calm_evening', focusArea: 'sleep', behaviorFamily: 'evening_wind_down', intensity: 'recovery', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'sleep_skip_late_caffeine', focusArea: 'sleep', behaviorFamily: 'late_stimulation', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'sleep_less_late_stimulation', focusArea: 'sleep', behaviorFamily: 'screen_cutoff', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'sleep_keep_wake_rhythm', focusArea: 'sleep', behaviorFamily: 'bedtime', intensity: 'normal', allowedModes: ['maintain'], eligibility: any },
  { id: 'sleep_earlier_bedtime', focusArea: 'sleep', behaviorFamily: 'bedtime', intensity: 'challenge', allowedModes: ['improve'], eligibility: any },
  { id: 'sleep_keep_wind_down', focusArea: 'sleep', behaviorFamily: 'evening_wind_down', intensity: 'micro', allowedModes: ['maintain'], eligibility: any },
  { id: 'sleep_park_unfinished_tasks', focusArea: 'sleep', behaviorFamily: 'next_day_parking', intensity: 'normal', allowedModes: ['improve'], eligibility: any },

  // nutrition — 18
  { id: 'nutrition_sit_down_lunch', focusArea: 'nutrition', behaviorFamily: 'meal_structure', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'nutrition_protein_next_meal', focusArea: 'nutrition', behaviorFamily: 'protein', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'nutrition_add_vegetables', focusArea: 'nutrition', behaviorFamily: 'vegetables', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'nutrition_simple_dinner', focusArea: 'nutrition', behaviorFamily: 'meal_structure', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'nutrition_prep_one_meal', focusArea: 'nutrition', behaviorFamily: 'meal_prep', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'nutrition_plan_next_meal', focusArea: 'nutrition', behaviorFamily: 'meal_prep', intensity: 'micro', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'nutrition_eat_without_screen', focusArea: 'nutrition', behaviorFamily: 'mindful_meal', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'nutrition_slow_the_meal', focusArea: 'nutrition', behaviorFamily: 'mindful_meal', intensity: 'micro', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'nutrition_swap_evening_snack', focusArea: 'nutrition', behaviorFamily: 'snack_swap', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  {
    id: 'nutrition_no_fast_food_today',
    focusArea: 'nutrition',
    behaviorFamily: 'fast_food',
    intensity: 'challenge',
    allowedModes: ['improve'],
    eligibility: { weekdayOk: true, weekendOk: true, requiresLessHealthyFoodRelevance: true },
  },
  { id: 'nutrition_less_processed_choice', focusArea: 'nutrition', behaviorFamily: 'less_processed', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'nutrition_keep_regular_meals', focusArea: 'nutrition', behaviorFamily: 'meal_structure', intensity: 'micro', allowedModes: ['maintain'], eligibility: any },
  { id: 'nutrition_one_grocery_choice', focusArea: 'nutrition', behaviorFamily: 'grocery', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'nutrition_pack_lunch', focusArea: 'nutrition', behaviorFamily: 'meal_prep', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'nutrition_protein_at_breakfast', focusArea: 'nutrition', behaviorFamily: 'protein', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'nutrition_keep_usual_dinner', focusArea: 'nutrition', behaviorFamily: 'meal_structure', intensity: 'micro', allowedModes: ['maintain'], eligibility: any },
  { id: 'nutrition_include_veg_at_dinner', focusArea: 'nutrition', behaviorFamily: 'vegetables', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'nutrition_eat_at_the_table', focusArea: 'nutrition', behaviorFamily: 'meal_structure', intensity: 'micro', allowedModes: ['improve', 'maintain'], eligibility: any },

  // alcohol — 11, improve only
  { id: 'alcohol_free_evening', focusArea: 'alcohol', behaviorFamily: 'alcohol_free', intensity: 'challenge', allowedModes: ['improve'], eligibility: any },
  { id: 'alcohol_free_first', focusArea: 'alcohol', behaviorFamily: 'alcohol_alternative', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'alcohol_set_limit_before', focusArea: 'alcohol', behaviorFamily: 'alcohol_limit', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'alcohol_alternate_drinks', focusArea: 'alcohol', behaviorFamily: 'alcohol_alternative', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'alcohol_delay_first', focusArea: 'alcohol', behaviorFamily: 'alcohol_limit', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'alcohol_smaller_amount', focusArea: 'alcohol', behaviorFamily: 'alcohol_limit', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'alcohol_social_without_default', focusArea: 'alcohol', behaviorFamily: 'alcohol_free', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'alcohol_change_home_cue', focusArea: 'alcohol', behaviorFamily: 'alcohol_free', intensity: 'challenge', allowedModes: ['improve'], eligibility: any },
  { id: 'alcohol_bring_alcohol_free', focusArea: 'alcohol', behaviorFamily: 'alcohol_alternative', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'alcohol_stop_at_the_plan', focusArea: 'alcohol', behaviorFamily: 'alcohol_limit', intensity: 'challenge', allowedModes: ['improve'], eligibility: any },
  { id: 'alcohol_start_with_food', focusArea: 'alcohol', behaviorFamily: 'alcohol_limit', intensity: 'micro', allowedModes: ['improve'], eligibility: any },

  // recovery — 16
  { id: 'recovery_phone_free_lunch', focusArea: 'recovery', behaviorFamily: 'phone_free_break', intensity: 'normal', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'recovery_ten_quiet_minutes', focusArea: 'recovery', behaviorFamily: 'quiet_break', intensity: 'micro', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'recovery_short_outdoor_reset', focusArea: 'recovery', behaviorFamily: 'outdoor_reset', intensity: 'micro', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'recovery_easy_walk', focusArea: 'recovery', behaviorFamily: 'easy_movement', intensity: 'micro', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'recovery_skip_extra_task', focusArea: 'recovery', behaviorFamily: 'evening_load', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'recovery_slow_breathing', focusArea: 'recovery', behaviorFamily: 'breathing', intensity: 'micro', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'recovery_after_work_pause', focusArea: 'recovery', behaviorFamily: 'evening_load', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'recovery_prepare_tomorrow', focusArea: 'recovery', behaviorFamily: 'evening_load', intensity: 'micro', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'recovery_easier_version', focusArea: 'recovery', behaviorFamily: 'easier_activity', intensity: 'recovery', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'recovery_screen_free_block', focusArea: 'recovery', behaviorFamily: 'phone_free_break', intensity: 'normal', allowedModes: ['improve'], eligibility: any },
  { id: 'recovery_keep_rest_habit', focusArea: 'recovery', behaviorFamily: 'quiet_break', intensity: 'micro', allowedModes: ['maintain'], eligibility: any },
  { id: 'recovery_gentle_mobility', focusArea: 'recovery', behaviorFamily: 'mobility', intensity: 'micro', allowedModes: ['improve', 'maintain'], eligibility: any },
  { id: 'recovery_leave_on_time', focusArea: 'recovery', behaviorFamily: 'evening_load', intensity: 'challenge', allowedModes: ['improve'], eligibility: any },
  { id: 'recovery_sit_outside', focusArea: 'recovery', behaviorFamily: 'outdoor_reset', intensity: 'micro', allowedModes: ['improve'], eligibility: any },
  { id: 'recovery_one_less_commitment', focusArea: 'recovery', behaviorFamily: 'evening_load', intensity: 'challenge', allowedModes: ['improve'], eligibility: any },
  { id: 'recovery_skip_extra_session', focusArea: 'recovery', behaviorFamily: 'easier_activity', intensity: 'recovery', allowedModes: ['improve', 'maintain'], eligibility: any },
] as const satisfies readonly DailyFocusActionDraft[];

export type DailyFocusActionId = (typeof DAILY_FOCUS_ACTION_DEFINITIONS)[number]['id'];
