/**
 * Figma: nordyan-coach-home
 * Optical scale aligned with approved Development / Health Score Explained density.
 */
export const coachLayout = {
  horizontalPadding: 24,
  scrollPaddingBottom: 28,
  headerPaddingTop: 8,
  headerGap: 12,
  headerTitleGap: 3,
  avatarSize: 56,
  avatarRingWidth: 2,
  identityGap: 12,
  contentGap: 10,
  sectionHeadingGap: 8,
  cardRadius: 14,
  cardPadding: 12,
  cardGap: 8,
  planHeaderGap: 8,
  durationPillRadius: 12,
  durationPillPaddingHorizontal: 10,
  durationPillPaddingVertical: 3,
  askIntroGap: 10,
  chipGap: 8,
  chipRadius: 12,
  chipPaddingHorizontal: 12,
  chipPaddingVertical: 8,
  inputHeight: 44,
  inputRadius: 14,
  sendButtonSize: 32,
  answerCardRadius: 14,
  answerCardPadding: 12,
} as const;

export const coachTypography = {
  screenTitleSize: 24,
  coachLabelSize: 11,
  coachSubtitleSize: 12,
  sectionHeadingSize: 10,
  focusTitleSize: 14,
  focusBodySize: 12,
  planTitleSize: 15,
  planDurationSize: 11,
  planBodySize: 12,
  planFrequencySize: 11,
  detailsSize: 11,
  askIntroSize: 12,
  chipSize: 12,
  inputSize: 13,
  footnoteSize: 10,
  answerQuestionSize: 11,
  answerBodySize: 12,
  messageSize: 12,
} as const;
