/**
 * Figma: nordyan-development-home (design frozen)
 * Optical scale tuned for system fonts so density matches the Figma artboard on device.
 */
export const developmentLayout = {
  horizontalPadding: 24,
  scrollPaddingBottom: 28,
  headerPaddingTop: 8,
  headerPaddingBottom: 0,
  headerGap: 14,
  headerTitleGap: 4,
  backButtonSize: 36,
  backButtonRadius: 18,
  backIconSize: 16,
  heroPaddingTop: 16,
  heroPaddingBottom: 12,
  heroGap: 10,
  scoreRingSize: 132,
  changePillRadius: 16,
  changePillPaddingHorizontal: 12,
  changePillPaddingVertical: 5,
  sectionPaddingVertical: 8,
  factorsGap: 10,
  factorsCardRadius: 16,
  factorsCardPaddingHorizontal: 16,
  factorsCardPaddingVertical: 4,
  factorRowPaddingVertical: 8,
  factorIconSize: 20,
  factorIconRadius: 10,
  factorIconGlyphSize: 11,
  factorLabelGap: 10,
  coachCardRadius: 16,
  coachCardPadding: 16,
  coachCardGap: 10,
  coachDotSize: 6,
  coachHeaderGap: 8,
  coachMessageGap: 4,
  trendsCtaRadius: 14,
  trendsCtaPaddingHorizontal: 16,
  trendsCtaPaddingVertical: 12,
  trendsCtaIconSize: 18,
  trendsCtaMarginVertical: 8,
  /** Figma: nordyan-development-trends — compact optical scale (Home tokens unchanged) */
  trendsContentGap: 10,
  trendsHeaderPaddingTop: 6,
  trendsHeaderGap: 12,
  trendsHeaderTitleGap: 3,
  trendsBackButtonSize: 34,
  trendsBackButtonRadius: 17,
  trendsBackIconSize: 15,
  trendsScoreCardPadding: 12,
  trendsScoreCardRadius: 14,
  trendsScoreCardGap: 10,
  trendsChangePillRadius: 14,
  trendsChangePillPaddingHorizontal: 10,
  trendsChangePillPaddingVertical: 4,
  trendsPeriodSelectorHeight: 36,
  trendsPeriodSelectorPadding: 2,
  trendsPeriodOptionRadius: 14,
  trendsChartCardPadding: 12,
  trendsChartCardRadius: 14,
  trendsChartHeight: 96,
  trendsChartGap: 8,
  trendsMetricPillRadius: 14,
  trendsMetricPillPaddingHorizontal: 10,
  trendsMetricPillPaddingVertical: 5,
  trendsMetricGap: 6,
  trendsCoachCardPadding: 12,
  trendsCoachCardGap: 8,
  trendsFactorsCtaPadding: 14,
} as const;

export const developmentTypography = {
  titleSize: 26,
  subtitleSize: 13,
  scoreSize: 52,
  scoreBandSize: 10,
  changePillSize: 12,
  sectionHeadingSize: 14,
  factorLabelSize: 13,
  factorValueSize: 13,
  coachTagSize: 10,
  coachTitleSize: 13,
  coachBodySize: 13,
  trendsCtaSize: 14,
  trendsTitleSize: 24,
  trendsSubtitleSize: 12,
  trendsScoreValueSize: 32,
  trendsScoreMaxSize: 12,
  trendsScoreBandSize: 9,
  trendsChangePillSize: 11,
  trendsPeriodOptionSize: 11,
  trendsMetricPillSize: 11,
  trendsChartAxisSize: 10,
  trendsChartBubbleSize: 10,
  trendsChartEmptySize: 11,
  trendsCoachTagSize: 9,
  trendsCoachTitleSize: 12,
  trendsCoachBodySize: 12,
} as const;
