import { spacing } from './spacing';
import { typography } from './typography';

export const onboardingLayout = {
  statusBarHeight: 44,
  statusBarPaddingHorizontal: spacing.lg,
  brandSectionPaddingTop: 9,
  brandMarkWidth: 184,
  brandMarkHeight: 55,
  brandMarkGap: spacing.md,
  brandLogoMinHeight: 49,
  brandLogoLineHeight: 49,
  accentLineWidth: 48,
  accentLineHeight: 2,
  buttonHeight: 56,
  homeIndicatorWidth: 139,
  homeIndicatorHeight: 5,
  homeIndicatorPaddingTop: 21,
  homeIndicatorPaddingBottom: spacing.sm,
  contentPaddingBottom: spacing.xl,
  horizontalPadding: spacing.xl,
  brandSectionGap: spacing.lg,
  footerGap: spacing.lgAlt,
  backgroundBottomSolidHeight: 104,
  backgroundBottomFadeHeight: 232,
  promiseIntroPaddingTop: 140,
  promiseIntroPaddingHorizontal: 28,
  promiseHeaderGap: 12,
  promiseIntroGap: spacing.xl,
  promiseBodyLineHeight: 1.78,
} as const;

/** Figma: nordyan-onboarding-6-profile (design frozen) */
export const onboardingProfileLayout = {
  formAreaPaddingTop: 40,
  headerGap: spacing.sm,
  headerBottomSpacing: spacing.sm,
  formHeaderGap: spacing.xl,
  titleFontSize: 30,
  titleLetterSpacing: -0.3,
  formCardPadding: spacing.lgAlt,
  formCardRadius: 20,
  formCardGap: spacing.lg,
  formRowGap: spacing.md,
  sectionGap: 28,
  fieldHeight: 52,
  fieldPaddingHorizontal: spacing.md,
  fieldLabelGap: 10,
  choiceLabelGap: 12,
  choiceOptionGap: 10,
  genderIconSize: 22,
  genderCardMinHeight: 52,
  genderCardWithIconMinHeight: 76,
  genderIconLabelGap: spacing.sm,
  helpLinkMinHeight: 44,
  helpLinkGap: spacing.sm,
  helpIconSize: 18,
  helpChevronSize: 16,
  footerTopSpacing: 40,
  footerTopPadding: spacing.sm,
  scrollBottomPadding: spacing.lg,
} as const;

/** Figma: nordyan-onboarding-7-sa-mater-du (design frozen) */
export const onboardingMeasurementHelpLayout = {
  horizontalPadding: spacing.lg,
  bottomPadding: spacing.xxl,
  navPaddingTop: 12,
  navPaddingBottom: spacing.lgAlt,
  backIconSize: 24,
  backTouchSize: 44,
  titleSectionGap: 12,
  titleSectionPaddingBottom: spacing.xl,
  titleFontSize: typography.fontSize.xxl,
  subtitleFontSize: 15,
  cardsSpacerHeight: spacing.lg,
  cardGap: spacing.md,
  cardPadding: spacing.lgAlt,
  cardRadius: spacing.md,
  cardHeaderGap: 12,
  cardIconSize: 20,
  cardTitleFontSize: typography.fontSize.md,
  bulletGap: 10,
  bulletRowGap: 12,
  bulletSize: 6,
  bulletRadius: 3,
  bulletTextFontSize: typography.fontSize.sm,
  ctaPaddingTop: spacing.xxl,
} as const;

/** Figma: nordyan-onboarding-5-result (design frozen) */
export const onboardingResultLayout = {
  mountainOverlay: 'rgba(18, 20, 22, 0.84)',
  areaPaddingTop: spacing.md,
  areaGap: spacing.xl,
  headerGap: spacing.sm,
  cardsGap: spacing.md,
  titleFontSize: 28,
  overlineLetterSpacing: 0.6,
  metricCardPadding: spacing.lg,
  metricCardRadius: spacing.md,
  metricCopyGap: spacing.xs,
  metricLabelFontSize: 13,
  bodyFatValueFontSize: 36,
  healthScoreValueFontSize: 40,
  coachCardPadding: spacing.lg,
  coachCardGap: spacing.md,
  coachHeaderGap: spacing.sm,
  coachHeaderFontSize: 10,
  coachHeaderLetterSpacing: 1.5,
  coachHeadlineFontSize: 20,
  coachBodyFontSize: 15,
  footerGap: spacing.lg,
  scrollBottomPadding: spacing.md,
} as const;

/** Figma: nordyan-onboarding-measurement-choice (design frozen) */
export const onboardingMeasurementChoiceLayout = {
  contentPaddingTop: 72,
  headerGap: spacing.sm,
  bodyGap: spacing.xl,
  actionsGap: spacing.md,
  titleFontSize: 28,
  subtitleFontSize: 15,
  secondaryButtonMinHeight: 56,
} as const;
