/** Figma: nordyan-profile layout tokens */
export const profileLayout = {
  scrollTopPadding: 24,
  headerTopOffset: 28,
  titleTopInset: 10,
  scrollBottomPadding: 100,
  horizontalPadding: 24,
  sectionGap: 24,
  sectionLabelGap: 8,
  sectionLabelPaddingLeft: 16,
  sectionLabelPaddingBottom: 12,
  mountainHeaderHeight: 260,
  mountainFadeHeight: 148,
  headerCardPadding: 20,
  headerCardRadius: 20,
  headerAvatarSize: 56,
  headerAvatarRingWidth: 2,
  headerAvatarIconSize: 27,
  headerChevronSize: 16,
  headerContentGap: 16,
  headerTextGap: 2,
  settingsCardRadius: 16,
  rowPaddingHorizontal: 16,
  rowPaddingVertical: 14,
  rowIconGap: 14,
  rowTextGap: 2,
  iconWrapperSize: 32,
  iconWrapperRadius: 16,
  iconSize: 18,
  chevronSize: 14,
} as const;

export const profileTypography = {
  screenTitleSize: 28,
  headerNameSize: 18,
  headerEmailSize: 12,
  sectionLabelSize: 11,
  rowTitleSize: 14,
  rowSubtitleSize: 11,
} as const;

/** Figma: nordyan-profile-health-profile (design frozen) */
export const profileHealthProfileLayout = {
  horizontalPadding: 32,
  scrollPaddingTop: 16,
  scrollPaddingBottom: 40,
  sectionGap: 28,
  headerGap: 8,
  sectionLabelGap: 12,
  navBarHeight: 44,
  navBarPaddingHorizontal: 24,
  navBarPaddingVertical: 8,
  backIconSize: 24,
  titleFontSize: 28,
  helpRowMinHeight: 44,
  helpRowPaddingVertical: 10,
  helpLinkFontSize: 14,
  helpChevronSize: 20,
  measurementsCardGap: 20,
} as const;

/** Figma: nordyan-profile-health-data-sources (design frozen) */
export const profileHealthDataSourcesLayout = {
  horizontalPadding: 20,
  scrollPaddingTop: 8,
  scrollPaddingBottom: 32,
  sectionGap: 24,
  headerGap: 8,
  sourcesListGap: 12,
  backTouchSize: 40,
  backTouchPadding: 8,
  backIconSize: 24,
  titleFontSize: 28,
  subtitleFontSize: 15,
  sourceCardPadding: 18,
  sourceCardRadius: 16,
  sourceCardGap: 16,
  sourceCardHeaderGap: 14,
  sourceCardTextGap: 4,
  sourceIconBoxSize: 44,
  sourceIconBoxRadius: 10,
  sourceIconSize: 24,
  sourceTitleSize: 16,
  sourceDescriptionSize: 13,
  sourceStatusDotSize: 6,
  sourceStatusGap: 8,
  sourceStatusFontSize: 13,
  connectButtonPaddingHorizontal: 16,
  connectButtonPaddingVertical: 8,
  connectButtonRadius: 8,
  connectButtonFontSize: 13,
  comingSoonOpacity: 0.55,
  privacyCardPadding: 16,
  privacyCardRadius: 12,
  privacyCardGap: 12,
  privacyIconBoxSize: 32,
  privacyIconBoxRadius: 6,
  privacyIconSize: 18,
  privacyTitleSize: 14,
  privacyBodySize: 13,
  footerNoteSize: 12,
} as const;

/** Figma: nordyan-health-new-measurement (design frozen) */
export const healthNewMeasurementLayout = {
  horizontalPadding: 32,
  headerPaddingTop: 16,
  headerGap: 8,
  titleFontSize: 28,
  subtitleFontSize: 14,
  sectionPaddingTop: 28,
  sectionLabelGap: 12,
  measurementCardGap: 20,
  tipsPaddingTop: 20,
  helpPaddingTop: 28,
  buttonPaddingTop: 28,
  scrollPaddingBottom: 32,
  navBarHeight: 44,
  navBarPaddingHorizontal: 24,
  navBarPaddingVertical: 8,
  backIconSize: 24,
  helpRowMinHeight: 44,
  helpRowPaddingVertical: 10,
  helpLinkFontSize: 14,
  helpChevronSize: 16,
} as const;
