import type {
  HealthScoreInput,
  HealthScoreResult,
  HealthScoreValidationError,
} from './health-score.types';

export type HealthScoreSuccessTestVector = {
  kind: 'success';
  id: string;
  description: string;
  input: HealthScoreInput;
  expected: HealthScoreResult;
};

export type HealthScoreValidationTestVector = {
  kind: 'validation';
  id: string;
  description: string;
  validationNotes: string;
  input: HealthScoreInput;
  expectedError: HealthScoreValidationError;
};

export type HealthScoreTestVector = HealthScoreSuccessTestVector | HealthScoreValidationTestVector;

export const HEALTH_SCORE_TEST_AS_OF_DATE = '2026-07-26';

/**
 * Manual validation vectors for Health Score Engine v1.0.0.
 * Expected values are deterministic for asOfDate = HEALTH_SCORE_TEST_AS_OF_DATE.
 */
export const healthScoreSuccessTestVectors: HealthScoreSuccessTestVector[] = [
  {
    kind: 'success',
    id: 'lean-young-male-runner',
    description: 'Lean athletic male, age 26, very active',
    input: {
      dateOfBirth: '2000-03-15',
      gender: 'male',
      heightCm: 180,
      weightKg: 72,
      waistCm: 78,
      neckCm: 38,
      activityLevel: 'very_active',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 93,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 92,
        activity: 92,
        ageAdjustedHealth: 96,
      },
      metrics: {
        ageYears: 26,
        bmi: 22.222,
        whtr: 0.433,
        bodyFatPct: 10.127,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'normal',
        whtrRisk: 'moderate',
        bodyFatCategory: 'athlete',
      },
      explanation: {
        biggestStrength: 'activity',
        biggestOpportunity: 'age_adjusted_whtr',
        primaryDriver: 'activity',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'lean-young-female-yoga',
    description: 'Lean active female with hip, age 28',
    input: {
      dateOfBirth: '1998-06-10',
      gender: 'female',
      heightCm: 168,
      weightKg: 58,
      waistCm: 68,
      neckCm: 32,
      hipCm: 96,
      activityLevel: 'active',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 90,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 91,
        activity: 82,
        ageAdjustedHealth: 97,
      },
      metrics: {
        ageYears: 28,
        bmi: 20.55,
        whtr: 0.405,
        bodyFatPct: 23.799,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'normal',
        whtrRisk: 'moderate',
        bodyFatCategory: 'fitness',
      },
      explanation: {
        biggestStrength: 'whtr',
        biggestOpportunity: 'age_adjusted_whtr',
        primaryDriver: 'whtr',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'fit-middle-male',
    description: 'Fit middle-aged male, age 45',
    input: {
      dateOfBirth: '1981-01-20',
      gender: 'male',
      heightCm: 182,
      weightKg: 82,
      waistCm: 86,
      neckCm: 40,
      activityLevel: 'moderate',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 81,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 83,
        activity: 68,
        ageAdjustedHealth: 93,
      },
      metrics: {
        ageYears: 45,
        bmi: 24.755,
        whtr: 0.473,
        bodyFatPct: 15.011,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'normal',
        whtrRisk: 'moderate',
        bodyFatCategory: 'fitness',
      },
      explanation: {
        biggestStrength: 'body_fat',
        biggestOpportunity: 'activity',
        primaryDriver: 'body_fat',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'average-young-male',
    description: 'Average young male, age 31',
    input: {
      dateOfBirth: '1994-09-05',
      gender: 'male',
      heightCm: 175,
      weightKg: 78,
      waistCm: 88,
      neckCm: 39,
      activityLevel: 'light',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 71,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 74,
        activity: 50,
        ageAdjustedHealth: 88,
      },
      metrics: {
        ageYears: 31,
        bmi: 25.469,
        whtr: 0.503,
        bodyFatPct: 18.564,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'overweight',
        whtrRisk: 'elevated',
        bodyFatCategory: 'average',
      },
      explanation: {
        biggestStrength: 'age_adjusted_body_fat',
        biggestOpportunity: 'activity',
        primaryDriver: 'activity',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'average-middle-female',
    description: 'Average middle-aged female without hip, Deurenberg fallback, age 43',
    input: {
      dateOfBirth: '1982-11-12',
      gender: 'female',
      heightCm: 165,
      weightKg: 68,
      waistCm: 78,
      neckCm: 33,
      activityLevel: 'moderate',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 73,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 70,
        activity: 68,
        ageAdjustedHealth: 85,
      },
      metrics: {
        ageYears: 43,
        bmi: 24.977,
        whtr: 0.473,
        bodyFatPct: 34.462,
        bodyFatMethod: 'deurenberg',
      },
      bands: {
        bmiCategory: 'normal',
        whtrRisk: 'moderate',
        bodyFatCategory: 'high',
      },
      explanation: {
        biggestStrength: 'whtr',
        biggestOpportunity: 'body_fat',
        primaryDriver: 'whtr',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'overweight-male-40s',
    description: 'Overweight male, age 48 — onboarding-like profile',
    input: {
      dateOfBirth: '1978-07-24',
      gender: 'male',
      heightCm: 182,
      weightKg: 89,
      waistCm: 96,
      neckCm: 41,
      activityLevel: 'moderate',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 71,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 67,
        activity: 68,
        ageAdjustedHealth: 85,
      },
      metrics: {
        ageYears: 48,
        bmi: 26.869,
        whtr: 0.527,
        bodyFatPct: 21.686,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'overweight',
        whtrRisk: 'elevated',
        bodyFatCategory: 'average',
      },
      explanation: {
        biggestStrength: 'age_adjusted_body_fat',
        biggestOpportunity: 'whtr',
        primaryDriver: 'age_adjusted_body_fat',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'overweight-female-50s',
    description: 'Overweight female, age 52',
    input: {
      dateOfBirth: '1974-04-18',
      gender: 'female',
      heightCm: 162,
      weightKg: 76,
      waistCm: 88,
      neckCm: 34,
      activityLevel: 'light',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 47,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 38,
        activity: 50,
        ageAdjustedHealth: 68,
      },
      metrics: {
        ageYears: 52,
        bmi: 28.959,
        whtr: 0.543,
        bodyFatPct: 41.311,
        bodyFatMethod: 'deurenberg',
      },
      bands: {
        bmiCategory: 'overweight',
        whtrRisk: 'elevated',
        bodyFatCategory: 'very_high',
      },
      explanation: {
        biggestStrength: 'age_adjusted_body_fat',
        biggestOpportunity: 'body_fat',
        primaryDriver: 'body_fat',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'obese-male-55',
    description: 'Obese sedentary male, age 55',
    input: {
      dateOfBirth: '1971-02-02',
      gender: 'male',
      heightCm: 178,
      weightKg: 108,
      waistCm: 112,
      neckCm: 43,
      activityLevel: 'sedentary',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 34,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 23,
        activity: 35,
        ageAdjustedHealth: 61,
      },
      metrics: {
        ageYears: 55,
        bmi: 34.087,
        whtr: 0.629,
        bodyFatPct: 30.833,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'obesity',
        whtrRisk: 'high',
        bodyFatCategory: 'very_high',
      },
      explanation: {
        biggestStrength: 'age_adjusted_body_fat',
        biggestOpportunity: 'body_fat',
        primaryDriver: 'body_fat',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'obese-female-60',
    description: 'Obese sedentary female, age 59',
    input: {
      dateOfBirth: '1966-08-30',
      gender: 'female',
      heightCm: 160,
      weightKg: 92,
      waistCm: 98,
      neckCm: 35,
      activityLevel: 'sedentary',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 29,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 20,
        activity: 35,
        ageAdjustedHealth: 45,
      },
      metrics: {
        ageYears: 59,
        bmi: 35.937,
        whtr: 0.613,
        bodyFatPct: 51.295,
        bodyFatMethod: 'deurenberg',
      },
      bands: {
        bmiCategory: 'obesity',
        whtrRisk: 'high',
        bodyFatCategory: 'very_high',
      },
      explanation: {
        biggestStrength: 'age_adjusted_body_fat',
        biggestOpportunity: 'body_fat',
        primaryDriver: 'body_fat',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'athletic-male-lifter',
    description: 'Muscular athletic male with elevated BMI, age 34',
    input: {
      dateOfBirth: '1992-05-14',
      gender: 'male',
      heightCm: 185,
      weightKg: 92,
      waistCm: 84,
      neckCm: 42,
      activityLevel: 'very_active',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 87,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 83,
        activity: 92,
        ageAdjustedHealth: 94,
      },
      metrics: {
        ageYears: 34,
        bmi: 26.881,
        whtr: 0.454,
        bodyFatPct: 11.116,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'overweight',
        whtrRisk: 'moderate',
        bodyFatCategory: 'athlete',
      },
      explanation: {
        biggestStrength: 'activity',
        biggestOpportunity: 'bmi',
        primaryDriver: 'activity',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'athletic-female-cyclist',
    description: 'Athletic female cyclist with hip, age 30',
    input: {
      dateOfBirth: '1995-12-01',
      gender: 'female',
      heightCm: 170,
      weightKg: 63,
      waistCm: 70,
      neckCm: 31,
      hipCm: 94,
      activityLevel: 'very_active',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 92,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 91,
        activity: 92,
        ageAdjustedHealth: 96,
      },
      metrics: {
        ageYears: 30,
        bmi: 21.799,
        whtr: 0.412,
        bodyFatPct: 23.832,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'normal',
        whtrRisk: 'moderate',
        bodyFatCategory: 'fitness',
      },
      explanation: {
        biggestStrength: 'activity',
        biggestOpportunity: 'age_adjusted_whtr',
        primaryDriver: 'activity',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'older-lean-male-65',
    description: 'Lean older male, age 65',
    input: {
      dateOfBirth: '1961-03-08',
      gender: 'male',
      heightCm: 176,
      weightKg: 74,
      waistCm: 84,
      neckCm: 39,
      activityLevel: 'active',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 86,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 84,
        activity: 82,
        ageAdjustedHealth: 94,
      },
      metrics: {
        ageYears: 65,
        bmi: 23.889,
        whtr: 0.477,
        bodyFatPct: 15.21,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'normal',
        whtrRisk: 'moderate',
        bodyFatCategory: 'fitness',
      },
      explanation: {
        biggestStrength: 'body_fat',
        biggestOpportunity: 'age_adjusted_whtr',
        primaryDriver: 'body_fat',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'older-average-female-68',
    description: 'Average older female, age 67',
    input: {
      dateOfBirth: '1958-10-22',
      gender: 'female',
      heightCm: 158,
      weightKg: 64,
      waistCm: 82,
      neckCm: 33,
      activityLevel: 'light',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 54,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 47,
        activity: 50,
        ageAdjustedHealth: 77,
      },
      metrics: {
        ageYears: 67,
        bmi: 25.637,
        whtr: 0.519,
        bodyFatPct: 40.774,
        bodyFatMethod: 'deurenberg',
      },
      bands: {
        bmiCategory: 'overweight',
        whtrRisk: 'elevated',
        bodyFatCategory: 'very_high',
      },
      explanation: {
        biggestStrength: 'age_adjusted_body_fat',
        biggestOpportunity: 'body_fat',
        primaryDriver: 'body_fat',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'young-sedentary-male',
    description: 'Young sedentary male, age 24',
    input: {
      dateOfBirth: '2002-01-09',
      gender: 'male',
      heightCm: 177,
      weightKg: 84,
      waistCm: 92,
      neckCm: 40,
      activityLevel: 'sedentary',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 62,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 68,
        activity: 35,
        ageAdjustedHealth: 80,
      },
      metrics: {
        ageYears: 24,
        bmi: 26.812,
        whtr: 0.52,
        bodyFatPct: 20.438,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'overweight',
        whtrRisk: 'elevated',
        bodyFatCategory: 'average',
      },
      explanation: {
        biggestStrength: 'age_adjusted_body_fat',
        biggestOpportunity: 'activity',
        primaryDriver: 'activity',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'young-active-female-no-hip',
    description: 'Active female without hip measurement, Deurenberg fallback, age 27',
    input: {
      dateOfBirth: '1999-07-03',
      gender: 'female',
      heightCm: 166,
      weightKg: 61,
      waistCm: 72,
      neckCm: 31,
      activityLevel: 'active',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 86,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 85,
        activity: 82,
        ageAdjustedHealth: 92,
      },
      metrics: {
        ageYears: 27,
        bmi: 22.137,
        whtr: 0.434,
        bodyFatPct: 27.374,
        bodyFatMethod: 'deurenberg',
      },
      bands: {
        bmiCategory: 'normal',
        whtrRisk: 'moderate',
        bodyFatCategory: 'average',
      },
      explanation: {
        biggestStrength: 'whtr',
        biggestOpportunity: 'body_fat',
        primaryDriver: 'whtr',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'middle-high-whtr-male',
    description: 'Normal BMI but elevated WHtR male, age 50',
    input: {
      dateOfBirth: '1976-06-16',
      gender: 'male',
      heightCm: 180,
      weightKg: 81,
      waistCm: 98,
      neckCm: 40,
      activityLevel: 'light',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 65,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 65,
        activity: 50,
        ageAdjustedHealth: 82,
      },
      metrics: {
        ageYears: 50,
        bmi: 25,
        whtr: 0.544,
        bodyFatPct: 24.006,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'overweight',
        whtrRisk: 'elevated',
        bodyFatCategory: 'high',
      },
      explanation: {
        biggestStrength: 'age_adjusted_body_fat',
        biggestOpportunity: 'activity',
        primaryDriver: 'activity',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'underweight-young-female',
    description: 'Underweight young female with hip, age 22',
    input: {
      dateOfBirth: '2004-02-28',
      gender: 'female',
      heightCm: 172,
      weightKg: 54,
      waistCm: 62,
      neckCm: 29,
      hipCm: 88,
      activityLevel: 'moderate',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 84,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 86,
        activity: 68,
        ageAdjustedHealth: 98,
      },
      metrics: {
        ageYears: 22,
        bmi: 18.253,
        whtr: 0.36,
        bodyFatPct: 16.634,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'underweight',
        whtrRisk: 'low',
        bodyFatCategory: 'athlete',
      },
      explanation: {
        biggestStrength: 'whtr',
        biggestOpportunity: 'bmi',
        primaryDriver: 'whtr',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'other-gender-moderate',
    description: 'Other gender profile, age 36',
    input: {
      dateOfBirth: '1989-09-19',
      gender: 'other',
      heightCm: 174,
      weightKg: 77,
      waistCm: 86,
      neckCm: 37,
      activityLevel: 'moderate',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 60,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 51,
        activity: 68,
        ageAdjustedHealth: 75,
      },
      metrics: {
        ageYears: 36,
        bmi: 25.433,
        whtr: 0.494,
        bodyFatPct: 33.399,
        bodyFatMethod: 'deurenberg',
      },
      bands: {
        bmiCategory: 'overweight',
        whtrRisk: 'moderate',
        bodyFatCategory: 'very_high',
      },
      explanation: {
        biggestStrength: 'whtr',
        biggestOpportunity: 'body_fat',
        primaryDriver: 'body_fat',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'older-active-female-72',
    description: 'Active older female with hip, age 72',
    input: {
      dateOfBirth: '1954-05-05',
      gender: 'female',
      heightCm: 157,
      weightKg: 67,
      waistCm: 86,
      neckCm: 34,
      hipCm: 102,
      activityLevel: 'active',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 59,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 41,
        activity: 82,
        ageAdjustedHealth: 78,
      },
      metrics: {
        ageYears: 72,
        bmi: 27.182,
        whtr: 0.548,
        bodyFatPct: 37.598,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'overweight',
        whtrRisk: 'elevated',
        bodyFatCategory: 'very_high',
      },
      explanation: {
        biggestStrength: 'activity',
        biggestOpportunity: 'body_fat',
        primaryDriver: 'body_fat',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'middle-obese-active-male',
    description: 'Obese but active male, age 41',
    input: {
      dateOfBirth: '1984-12-11',
      gender: 'male',
      heightCm: 183,
      weightKg: 102,
      waistCm: 108,
      neckCm: 42,
      activityLevel: 'active',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 57,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 42,
        activity: 82,
        ageAdjustedHealth: 66,
      },
      metrics: {
        ageYears: 41,
        bmi: 30.458,
        whtr: 0.59,
        bodyFatPct: 28.33,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'obesity',
        whtrRisk: 'elevated',
        bodyFatCategory: 'high',
      },
      explanation: {
        biggestStrength: 'activity',
        biggestOpportunity: 'whtr',
        primaryDriver: 'whtr',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'lean-tall-male-29',
    description: 'Lean tall male, age 28',
    input: {
      dateOfBirth: '1997-08-17',
      gender: 'male',
      heightCm: 198,
      weightKg: 84,
      waistCm: 80,
      neckCm: 39,
      activityLevel: 'active',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 92,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 95,
        activity: 82,
        ageAdjustedHealth: 98,
      },
      metrics: {
        ageYears: 28,
        bmi: 21.426,
        whtr: 0.404,
        bodyFatPct: 8.15,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'normal',
        whtrRisk: 'moderate',
        bodyFatCategory: 'athlete',
      },
      explanation: {
        biggestStrength: 'whtr',
        biggestOpportunity: 'age_adjusted_whtr',
        primaryDriver: 'whtr',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'petite-overweight-female-47',
    description: 'Petite overweight sedentary female, age 47',
    input: {
      dateOfBirth: '1979-03-27',
      gender: 'female',
      heightCm: 152,
      weightKg: 68,
      waistCm: 86,
      neckCm: 32,
      activityLevel: 'sedentary',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 40,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 34,
        activity: 35,
        ageAdjustedHealth: 64,
      },
      metrics: {
        ageYears: 47,
        bmi: 29.432,
        whtr: 0.566,
        bodyFatPct: 40.729,
        bodyFatMethod: 'deurenberg',
      },
      bands: {
        bmiCategory: 'overweight',
        whtrRisk: 'elevated',
        bodyFatCategory: 'very_high',
      },
      explanation: {
        biggestStrength: 'age_adjusted_body_fat',
        biggestOpportunity: 'body_fat',
        primaryDriver: 'body_fat',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'edge-min-height',
    description: 'Edge case: minimum accepted height (120 cm)',
    input: {
      dateOfBirth: '1990-01-01',
      gender: 'female',
      heightCm: 120,
      weightKg: 45,
      waistCm: 58,
      neckCm: 28,
      hipCm: 82,
      activityLevel: 'moderate',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 69,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 68,
        activity: 68,
        ageAdjustedHealth: 90,
      },
      metrics: {
        ageYears: 36,
        bmi: 31.25,
        whtr: 0.483,
        bodyFatPct: 26.428,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'obesity',
        whtrRisk: 'moderate',
        bodyFatCategory: 'average',
      },
      explanation: {
        biggestStrength: 'age_adjusted_body_fat',
        biggestOpportunity: 'bmi',
        primaryDriver: 'bmi',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'edge-max-height',
    description: 'Edge case: maximum accepted height (230 cm)',
    input: {
      dateOfBirth: '1993-04-12',
      gender: 'male',
      heightCm: 230,
      weightKg: 110,
      waistCm: 92,
      neckCm: 42,
      activityLevel: 'active',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 89,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 95,
        activity: 82,
        ageAdjustedHealth: 98,
      },
      metrics: {
        ageYears: 33,
        bmi: 20.794,
        whtr: 0.4,
        bodyFatPct: 11.006,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'normal',
        whtrRisk: 'moderate',
        bodyFatCategory: 'athlete',
      },
      explanation: {
        biggestStrength: 'whtr',
        biggestOpportunity: 'age_adjusted_whtr',
        primaryDriver: 'whtr',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'edge-min-weight',
    description: 'Edge case: minimum accepted weight (35 kg)',
    input: {
      dateOfBirth: '2001-06-20',
      gender: 'female',
      heightCm: 162,
      weightKg: 35,
      waistCm: 56,
      neckCm: 27,
      hipCm: 80,
      activityLevel: 'light',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 74,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 77,
        activity: 50,
        ageAdjustedHealth: 95,
      },
      metrics: {
        ageYears: 25,
        bmi: 13.336,
        whtr: 0.346,
        bodyFatPct: 11.772,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'underweight',
        whtrRisk: 'low',
        bodyFatCategory: 'athlete',
      },
      explanation: {
        biggestStrength: 'body_fat',
        biggestOpportunity: 'bmi',
        primaryDriver: 'body_fat',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'edge-athlete-high-bmi',
    description: 'Edge case: athlete with high BMI but low body fat',
    input: {
      dateOfBirth: '1991-11-03',
      gender: 'male',
      heightCm: 178,
      weightKg: 95,
      waistCm: 82,
      neckCm: 41,
      activityLevel: 'very_active',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 84,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 77,
        activity: 92,
        ageAdjustedHealth: 94,
      },
      metrics: {
        ageYears: 34,
        bmi: 29.984,
        whtr: 0.461,
        bodyFatPct: 11.389,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'overweight',
        whtrRisk: 'moderate',
        bodyFatCategory: 'athlete',
      },
      explanation: {
        biggestStrength: 'activity',
        biggestOpportunity: 'bmi',
        primaryDriver: 'activity',
      },
      computedAt: '2026-07-26',
    },
  },
  {
    kind: 'success',
    id: 'edge-extremely-low-waist',
    description: 'Edge case: extremely low waist within accepted bounds',
    input: {
      dateOfBirth: '1996-02-14',
      gender: 'male',
      heightCm: 190,
      weightKg: 78,
      waistCm: 55,
      neckCm: 20,
      activityLevel: 'active',
      asOfDate: '2026-07-26',
    },
    expected: {
      score: 88,
      scoreVersion: '1.0.0',
      subscores: {
        bodyComposition: 89,
        activity: 82,
        ageAdjustedHealth: 93,
      },
      metrics: {
        ageYears: 30,
        bmi: 21.607,
        whtr: 0.289,
        bodyFatPct: 3.494,
        bodyFatMethod: 'us_navy',
      },
      bands: {
        bmiCategory: 'normal',
        whtrRisk: 'low',
        bodyFatCategory: 'athlete',
      },
      explanation: {
        biggestStrength: 'body_fat',
        biggestOpportunity: 'age_adjusted_whtr',
        primaryDriver: 'body_fat',
      },
      computedAt: '2026-07-26',
    },
  },
];

/**
 * Validation behaviour:
 * - Reject malformed ISO dates before scoring.
 * - Reject derived age outside 18–100.
 * - Reject waistCm <= neckCm before range checks.
 * - Reject measurements outside INPUT_LIMITS.
 * - Reject non-finite or out-of-range body fat estimates after validation.
 */
export const healthScoreValidationTestVectors: HealthScoreValidationTestVector[] = [
  {
    kind: 'validation',
    id: 'invalid-height-below-min',
    description: 'Invalid: height below minimum accepted value',
    validationNotes: 'Reject before scoring because heightCm must stay within INPUT_LIMITS.heightCm.',
    input: {
      dateOfBirth: '1990-01-01',
      gender: 'male',
      heightCm: 119,
      weightKg: 70,
      waistCm: 80,
      neckCm: 38,
      activityLevel: 'moderate',
      asOfDate: '2026-07-26',
    },
    expectedError: {
      code: 'VALIDATION',
      message: 'heightCm is outside the supported range.',
    },
  },
  {
    kind: 'validation',
    id: 'invalid-height-above-max',
    description: 'Invalid: height above maximum accepted value',
    validationNotes: 'Reject before scoring because heightCm must stay within INPUT_LIMITS.heightCm.',
    input: {
      dateOfBirth: '1990-01-01',
      gender: 'male',
      heightCm: 231,
      weightKg: 110,
      waistCm: 92,
      neckCm: 40,
      activityLevel: 'moderate',
      asOfDate: '2026-07-26',
    },
    expectedError: {
      code: 'VALIDATION',
      message: 'heightCm is outside the supported range.',
    },
  },
  {
    kind: 'validation',
    id: 'invalid-weight-below-min',
    description: 'Invalid: weight below minimum accepted value',
    validationNotes: 'Reject before scoring because weightKg must stay within INPUT_LIMITS.weightKg.',
    input: {
      dateOfBirth: '1990-01-01',
      gender: 'female',
      heightCm: 165,
      weightKg: 34,
      waistCm: 70,
      neckCm: 32,
      activityLevel: 'moderate',
      asOfDate: '2026-07-26',
    },
    expectedError: {
      code: 'VALIDATION',
      message: 'weightKg is outside the supported range.',
    },
  },
  {
    kind: 'validation',
    id: 'invalid-age-under-18',
    description: 'Invalid: age below supported minimum',
    validationNotes: 'Reject before scoring because derived age must be between 18 and 100.',
    input: {
      dateOfBirth: '2010-01-01',
      gender: 'male',
      heightCm: 175,
      weightKg: 70,
      waistCm: 80,
      neckCm: 38,
      activityLevel: 'moderate',
      asOfDate: '2026-07-26',
    },
    expectedError: {
      code: 'VALIDATION',
      message: 'Age must be between 18 and 100 years.',
    },
  },
  {
    kind: 'validation',
    id: 'invalid-waist-not-greater-than-neck',
    description: 'Invalid: waist must be greater than neck for anthropometric formulas',
    validationNotes: 'Reject before scoring because waistCm <= neckCm breaks Navy body fat estimation.',
    input: {
      dateOfBirth: '1990-01-01',
      gender: 'male',
      heightCm: 175,
      weightKg: 70,
      waistCm: 45,
      neckCm: 45,
      activityLevel: 'moderate',
      asOfDate: '2026-07-26',
    },
    expectedError: {
      code: 'VALIDATION',
      message: 'waistCm must be greater than neckCm.',
    },
  },
  {
    kind: 'validation',
    id: 'invalid-date-of-birth',
    description: 'Invalid: malformed dateOfBirth',
    validationNotes: 'Reject before scoring because dateOfBirth must match YYYY-MM-DD ISO format.',
    input: {
      dateOfBirth: 'not-a-date',
      gender: 'male',
      heightCm: 175,
      weightKg: 70,
      waistCm: 80,
      neckCm: 38,
      activityLevel: 'moderate',
      asOfDate: '2026-07-26',
    },
    expectedError: {
      code: 'VALIDATION',
      message: 'dateOfBirth must be a valid ISO date string.',
    },
  },
  {
    kind: 'validation',
    id: 'invalid-as-of-date',
    description: 'Invalid: malformed asOfDate',
    validationNotes: 'Reject before scoring because asOfDate must match YYYY-MM-DD ISO format.',
    input: {
      dateOfBirth: '1990-01-01',
      gender: 'male',
      heightCm: 175,
      weightKg: 70,
      waistCm: 80,
      neckCm: 38,
      activityLevel: 'moderate',
      asOfDate: '2026/07/26',
    },
    expectedError: {
      code: 'VALIDATION',
      message: 'asOfDate must be a valid ISO date string.',
    },
  },
];

export const healthScoreTestVectors: HealthScoreTestVector[] = [
  ...healthScoreSuccessTestVectors,
  ...healthScoreValidationTestVectors,
];
